Customized bash_powerline

diff --git a/bash_powerline b/bash_powerline
--- a/bash_powerline
+++ b/bash_powerline
@@ -4,108 +4,159 @@
 
 __powerline() {
 
-    # Unicode symbols
-    readonly PS_SYMBOL_DARWIN=''
-    readonly PS_SYMBOL_LINUX='$'
-    readonly PS_SYMBOL_OTHER='%'
-    readonly GIT_BRANCH_SYMBOL='⑂ '
-    readonly GIT_BRANCH_CHANGED_SYMBOL='+'
-    readonly GIT_NEED_PUSH_SYMBOL='⇡'
-    readonly GIT_NEED_PULL_SYMBOL='⇣'
+  # Unicode symbols
+  readonly PS_SYMBOL_DARWIN=''
+  readonly PS_SYMBOL_LINUX='$'
+  readonly PS_SYMBOL_OTHER='%'
+  readonly GIT_BRANCH_SYMBOL='⑂'
+  readonly GIT_BRANCH_CHANGED_SYMBOL='+'
+  readonly GIT_NEED_PUSH_SYMBOL='⇡'
+  readonly GIT_NEED_PULL_SYMBOL='⇣'
+  readonly RUBY_SYMBOL='⬙'
+  readonly NODE_SYMBOL='⬢'
 
-    # Solarized colorscheme
-    readonly FG_BASE03="\[$(tput setaf 8)\]"
-    readonly FG_BASE02="\[$(tput setaf 0)\]"
-    readonly FG_BASE01="\[$(tput setaf 10)\]"
-    readonly FG_BASE00="\[$(tput setaf 11)\]"
-    readonly FG_BASE0="\[$(tput setaf 12)\]"
-    readonly FG_BASE1="\[$(tput setaf 14)\]"
-    readonly FG_BASE2="\[$(tput setaf 7)\]"
-    readonly FG_BASE3="\[$(tput setaf 15)\]"
+  function __tput { tput $* 2> /dev/null; }
 
-    readonly BG_BASE03="\[$(tput setab 8)\]"
-    readonly BG_BASE02="\[$(tput setab 0)\]"
-    readonly BG_BASE01="\[$(tput setab 10)\]"
-    readonly BG_BASE00="\[$(tput setab 11)\]"
-    readonly BG_BASE0="\[$(tput setab 12)\]"
-    readonly BG_BASE1="\[$(tput setab 14)\]"
-    readonly BG_BASE2="\[$(tput setab 7)\]"
-    readonly BG_BASE3="\[$(tput setab 15)\]"
+  readonly FG_BLACK="\[$(__tput setaf 0)\]"
 
-    readonly FG_YELLOW="\[$(tput setaf 3)\]"
-    readonly FG_ORANGE="\[$(tput setaf 9)\]"
-    readonly FG_RED="\[$(tput setaf 1)\]"
-    readonly FG_MAGENTA="\[$(tput setaf 5)\]"
-    readonly FG_VIOLET="\[$(tput setaf 13)\]"
-    readonly FG_BLUE="\[$(tput setaf 4)\]"
-    readonly FG_CYAN="\[$(tput setaf 6)\]"
-    readonly FG_GREEN="\[$(tput setaf 2)\]"
+  readonly FG_GRAY1="\[$(__tput setaf 15)\]"
+  readonly FG_GRAY2="\[$(__tput setaf 7)\]"
+  readonly FG_GRAY3="\[$(__tput setaf 8)\]"
 
-    readonly BG_YELLOW="\[$(tput setab 3)\]"
-    readonly BG_ORANGE="\[$(tput setab 9)\]"
-    readonly BG_RED="\[$(tput setab 1)\]"
-    readonly BG_MAGENTA="\[$(tput setab 5)\]"
-    readonly BG_VIOLET="\[$(tput setab 13)\]"
-    readonly BG_BLUE="\[$(tput setab 4)\]"
-    readonly BG_CYAN="\[$(tput setab 6)\]"
-    readonly BG_GREEN="\[$(tput setab 2)\]"
+  readonly FG_RED="\[$(__tput setaf 9)\]"
+  readonly FG_GREEN="\[$(__tput setaf 10)\]"
+  readonly FG_YELLOW="\[$(__tput setaf 11)\]"
+  readonly FG_BLUE="\[$(__tput setaf 12)\]"
+  readonly FG_MAGENTA="\[$(__tput setaf 13)\]"
+  readonly FG_CYAN="\[$(__tput setaf 14)\]"
 
-    readonly DIM="\[$(tput dim)\]"
-    readonly REVERSE="\[$(tput rev)\]"
-    readonly RESET="\[$(tput sgr0)\]"
-    readonly BOLD="\[$(tput bold)\]"
+  readonly FG_DARK_RED="\[$(__tput setaf 1)\]"
+  readonly FG_DARK_GREEN="\[$(__tput setaf 2)\]"
+  readonly FG_MUSTARD="\[$(__tput setaf 3)\]"
+  readonly FG_NAVY="\[$(__tput setaf 4)\]"
+  readonly FG_PURPLE="\[$(__tput setaf 5)\]"
+  readonly FG_TURQUOISE="\[$(__tput setaf 6)\]"
 
-    # what OS?
-    case "$(uname)" in
-        Darwin)
-            readonly PS_SYMBOL=$PS_SYMBOL_DARWIN
-            ;;
-        Linux)
-            readonly PS_SYMBOL=$PS_SYMBOL_LINUX
-            ;;
-        *)
-            readonly PS_SYMBOL=$PS_SYMBOL_OTHER
-    esac
+  readonly BG_BLACK="\[$(__tput setab 0)\]"
 
-    __git_info() {
-        [ -x "$(which git)" ] || return    # git not found
+  readonly BG_GRAY1="\[$(__tput setab 15)\]"
+  readonly BG_GRAY2="\[$(__tput setab 7)\]"
+  readonly BG_GRAY3="\[$(__tput setab 8)\]"
 
-        local git_eng="env LANG=C git"   # force git output in English to make our work easier
-        # get current branch name or short SHA1 hash for detached head
-        local branch="$($git_eng symbolic-ref --short HEAD 2>/dev/null || $git_eng describe --tags --always 2>/dev/null)"
-        [ -n "$branch" ] || return  # git branch not found
+  readonly BG_RED="\[$(__tput setab 9)\]"
+  readonly BG_GREEN="\[$(__tput setab 10)\]"
+  readonly BG_YELLOW="\[$(__tput setab 11)\]"
+  readonly BG_BLUE="\[$(__tput setab 12)\]"
+  readonly BG_MAGENTA="\[$(__tput setab 13)\]"
+  readonly BG_CYAN="\[$(__tput setab 14)\]"
 
-        local marks
+  readonly BG_DARK_RED="\[$(__tput setab 1)\]"
+  readonly BG_DARK_GREEN="\[$(__tput setab 2)\]"
+  readonly BG_MUSTARD="\[$(__tput setab 3)\]"
+  readonly BG_NAVY="\[$(__tput setab 4)\]"
+  readonly BG_PURPLE="\[$(__tput setab 5)\]"
+  readonly BG_TURQUOISE="\[$(__tput setab 6)\]"
 
-        # branch is modified?
-        [ -n "$($git_eng status --porcelain)" ] && marks+=" $GIT_BRANCH_CHANGED_SYMBOL"
+  readonly BG_DEEP_GREEN="\[$(__tput setab 22)\]"
 
-        # how many commits local branch is ahead/behind of remote?
-        local stat="$($git_eng status --porcelain --branch | grep '^##' | grep -o '\[.\+\]$')"
-        local aheadN="$(echo $stat | grep -o 'ahead [[:digit:]]\+' | grep -o '[[:digit:]]\+')"
-        local behindN="$(echo $stat | grep -o 'behind [[:digit:]]\+' | grep -o '[[:digit:]]\+')"
-        [ -n "$aheadN" ] && marks+=" $GIT_NEED_PUSH_SYMBOL$aheadN"
-        [ -n "$behindN" ] && marks+=" $GIT_NEED_PULL_SYMBOL$behindN"
+  readonly DIM="\[$(__tput dim)\]"
+  readonly REVERSE="\[$(__tput rev)\]"
+  readonly RESET="\[$(__tput sgr0)\]"
+  readonly BOLD="\[$(__tput bold)\]"
 
-        # print the git branch segment without a trailing newline
-p        printf " $GIT_BRANCH_SYMBOL$branch$marks "
-    }
+  # what OS?
+  case "$(uname)" in
+    Darwin)
+      readonly PS_SYMBOL=$PS_SYMBOL_DARWIN
+      ;;
+    Linux)
+      readonly PS_SYMBOL=$PS_SYMBOL_LINUX
+      ;;
+    *)
+      readonly PS_SYMBOL=$PS_SYMBOL_OTHER
+  esac
 
-    ps1() {
-        # Check the exit code of the previous command and display different
-        # colors in the prompt accordingly.
-        if [ $? -eq 0 ]; then
-            local BG_EXIT="$BG_GREEN"
-        else
-            local BG_EXIT="$BG_RED"
-        fi
+  ### Ruby #######################################################
+  if [ `which rbenv 2> /dev/null` ]; then
+      __ruby_version() { printf $(rbenv version-name); }
+  elif [ `which ruby 2> /dev/null` ]; then
+      __ruby_version() { printf $(ruby --version | cut -d' ' -f2); }
+  else
+    __ruby_version() { return; }
+  fi
 
-        PS1="$BG_BASE1$FG_BASE3 \w $RESET"
-        PS1+="$BG_BLUE$FG_BASE3$(__git_info)$RESET"
-        PS1+="$BG_EXIT$FG_BASE3 $PS_SYMBOL $RESET "
-    }
+  __ruby_info() {
+    [ -z "$(__ruby_version)" ] && return
+    printf " $RUBY_SYMBOL $(__ruby_version) "
+  }
 
-    PROMPT_COMMAND=ps1
+  ### Node.js ####################################################
+  if [ `which nodenv 2> /dev/null` ]; then
+    __node_version() { printf $(nodenv version-name); }
+  elif [ `which node 2> /dev/null` ]; then
+    __node_version() { printf $(node -v | cut -d'v' -f2); }
+  else
+    __node_version() { return; }
+  fi
+
+  __node_info() {
+    [ -z "$(__node_version)" ] && return
+    printf " $NODE_SYMBOL $(__node_version) "
+  }
+
+  ### Git ########################################################
+  __git_info() {
+    [ -x "$(which git)" ] || return    # git not found
+
+    local git_eng="env LANG=C git"   # force git output in English to make our work easier
+    # get current branch name or short SHA1 hash for detached head
+    local branch="$($git_eng symbolic-ref --short HEAD 2>/dev/null || $git_eng describe --tags --always 2>/dev/null)"
+    [ -n "$branch" ] || return  # git branch not found
+
+    local marks
+
+    # branch is modified?
+    [ -n "$($git_eng status --porcelain)" ] && marks+=" $GIT_BRANCH_CHANGED_SYMBOL"
+
+    # how many commits local branch is ahead/behind of remote?
+    local stat="$($git_eng status --porcelain --branch | grep '^##' | grep -o '\[.\+\]$')"
+    local aheadN="$(echo $stat | grep -o 'ahead [[:digit:]]\+' | grep -o '[[:digit:]]\+')"
+    local behindN="$(echo $stat | grep -o 'behind [[:digit:]]\+' | grep -o '[[:digit:]]\+')"
+    [ -n "$aheadN" ] && marks+=" $GIT_NEED_PUSH_SYMBOL$aheadN"
+    [ -n "$behindN" ] && marks+=" $GIT_NEED_PULL_SYMBOL$behindN"
+
+    printf " $GIT_BRANCH_SYMBOL $branch$marks "
+  }
+
+  ### PROMPT #####################################################
+  case $TERM in
+    xterm*|rxvt|Eterm|eterm)
+      title() { echo -ne "\033]0;${USER}@${HOSTNAME%%.*}\007"; }
+      ;;
+    screen)
+      title() { echo -ne "\033_${USER}@${HOSTNAME%%.*}\033\\"; }
+    ;;
+  esac
+
+  ps1() {
+    # Check the exit code of the previous command and display different
+    # colors in the prompt accordingly.
+    if [ $? -eq 0 ]; then
+      local BG_EXIT="$BG_DARK_GREEN"
+    else
+      local BG_EXIT="$BG_RED"
+    fi
+
+    PS1="\n$BG_GRAY3$FG_GRAY1 \s $RESET"
+    PS1+="$BG_MUSTARD$FG_BLACK \w $RESET"
+    PS1+="$BG_DARK_RED$FG_GRAY1$(__ruby_info)$RESET"
+    PS1+="$BG_DEEP_GREEN$FG_GRAY1$(__node_info)$RESET"
+    PS1+="$BG_BLUE$FG_GRAY1$(__git_info)$RESET\n"
+    PS1+="$BG_GRAY2$FG_BLACK \u@\h $RESET"
+    PS1+="$BG_EXIT$FG_GRAY1 $PS_SYMBOL $RESET "
+  }
+
+  PROMPT_COMMAND="ps1 && title"
 }
 
 __powerline
